esphome:
  name: energy-meter
  friendly_name: energy-meter

bk72xx:
  board: generic-bk7231t-qfn32-tuya

logger:
mdns:
ota:
debug:
prometheus:

api:
  reboot_timeout: 0s
  
web_server:
  local: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

button:
  - platform: restart
    name: Restart

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: Wifi Signal
  - platform: hlw8012
    id: BL0937
    model: BL0937
    update_interval: 1s
    change_mode_every: 3
    cf_pin:
      number: P9
      inverted: true
    cf1_pin:
      number: P8
      inverted: true
    sel_pin:
      number: P24
      inverted: true
    power:
      name: BL0937 Power
      unit_of_measurement: W
      accuracy_decimals: 0
      filters:
        - median:
            window_size: 7
            send_every: 4
            send_first_at: 3
        - calibrate_linear:
            - 0.0 -> 0.0
            - 4.1 -> 2.7
            - 8.1 -> 5.0
            - 12.2 -> 8.2
            - 3020 -> 1900
#    current:
#      name: BL0937 Current
#      unit_of_measurement: A
#      accuracy_decimals: 3
#    voltage:
#      name: BL0937 Voltage
#      unit_of_measurement: V
#      accuracy_decimals: 1
#    energy:
#      name: BL0937 Energy
    
status_led:
  pin:
    number: P6
    inverted: true
